build:
  stage: build
  script:
  - apt-get update -qq && apt-get install -y -qq libboost-all-dev unzip
  - git clone https://github.com/tensorflow/tensorflow
  - cd tensorflow && git checkout r1.9 && cd ..
  - cd tensorflow && tensorflow/contrib/lite/download_dependencies.sh && cd ..
  - cd tensorflow && make -s -j4 -f tensorflow/contrib/lite/Makefile && cd ..
  - CXXFLAGS=-isystem\ $PWD/tensorflow\ -isystem\ $PWD/tensorflow/tensorflow/contrib/lite/downloads/flatbuffers/include LDFLAGS=-L\ $(ls -d $PWD/tensorflow/tensorflow/contrib/lite/gen/lib/*)\ -ltensorflow-lite meson build --buildtype release --werror --warnlevel 3 --default-library static
  - ninja -C build
  - doxygen

release:
  stage: deploy
  script:
  - doxygen && mv html docs
  artifacts:
    name: "libaction-$CI_COMMIT_REF_NAME"
    paths:
    - docs
    - include
  only:
  - tags

pages:
  stage: deploy
  script:
  - doxygen && mv html public
  artifacts:
    paths:
    - public
  only:
  - tags
